CREATE DATABASE IF NOT EXISTS ecotrack_analytics;
USE ecotrack_analytics;

CREATE TABLE companies (
    Company_ID VARCHAR(20) PRIMARY KEY,
    Signup_Date DATE,
    Industry VARCHAR(50),
    Country VARCHAR(30),
    Company_Size VARCHAR(30),
    Employees INT,
    Plan VARCHAR(30),
    Monthly_Fee DECIMAL(10,2),
    Contract_Type VARCHAR(20),
    Acquisition_Channel VARCHAR(40),
    Reduction_Target_Pct DECIMAL(6,2),
    Avg_Monthly_Logins DECIMAL(8,2),
    Avg_Reports_Generated DECIMAL(8,2),
    Avg_Data_Completeness_Pct DECIMAL(6,2),
    Initial_CO2_kg DECIMAL(14,2),
    Latest_CO2_kg DECIMAL(14,2),
    Observed_Reduction_Pct DECIMAL(8,2),
    Churn_Status VARCHAR(20),
    Churn_Date DATE NULL,
    Months_Active INT,
    Lifetime_Revenue DECIMAL(14,2),
    Churn_Flag INT,
    Signup_Month VARCHAR(7),
    Annualised_Revenue DECIMAL(14,2)
);

CREATE TABLE monthly_sustainability (
    Company_ID VARCHAR(20),
    Month DATE,
    Industry VARCHAR(50),
    Country VARCHAR(30),
    Company_Size VARCHAR(30),
    Employees INT,
    Plan VARCHAR(30),
    Monthly_Fee DECIMAL(10,2),
    Contract_Type VARCHAR(20),
    Acquisition_Channel VARCHAR(40),
    Electricity_kWh DECIMAL(14,2),
    Gas_kWh DECIMAL(14,2),
    Fuel_Litres DECIMAL(14,2),
    Business_Travel_km DECIMAL(14,2),
    Waste_kg DECIMAL(14,2),
    Water_Litres DECIMAL(14,2),
    Electricity_CO2_kg DECIMAL(14,2),
    Gas_CO2_kg DECIMAL(14,2),
    Fuel_CO2_kg DECIMAL(14,2),
    Travel_CO2_kg DECIMAL(14,2),
    Waste_CO2_kg DECIMAL(14,2),
    Total_CO2_kg DECIMAL(14,2),
    Reduction_Target_Pct DECIMAL(6,2),
    Monthly_Logins INT,
    Reports_Generated INT,
    Targets_Set INT,
    Recommendations_Viewed INT,
    Data_Completeness_Pct DECIMAL(6,2),
    MRR DECIMAL(10,2),
    Is_Active INT,
    CO2_tonnes DECIMAL(14,4),
    CO2_per_Employee_kg DECIMAL(14,4),
    PRIMARY KEY (Company_ID, Month)
);
